# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  joint11:
    has_velocity_limits: true
    max_velocity: 3.1416
    has_acceleration_limits: false
    max_acceleration: 0
  joint12:
    has_velocity_limits: true
    max_velocity: 3.1416
    has_acceleration_limits: false
    max_acceleration: 0
  joint13:
    has_velocity_limits: true
    max_velocity: 3.4907
    has_acceleration_limits: false
    max_acceleration: 0
  joint14:
    has_velocity_limits: true
    max_velocity: 6.1087
    has_acceleration_limits: false
    max_acceleration: 0
  joint15:
    has_velocity_limits: true
    max_velocity: 6.1087
    has_acceleration_limits: false
    max_acceleration: 0
  joint16:
    has_velocity_limits: true
    max_velocity: 6.9813
    has_acceleration_limits: false
    max_acceleration: 0
  joint21:
    has_velocity_limits: true
    max_velocity: 3.1416
    has_acceleration_limits: false
    max_acceleration: 0
  joint22:
    has_velocity_limits: true
    max_velocity: 3.1416
    has_acceleration_limits: false
    max_acceleration: 0
  joint23:
    has_velocity_limits: true
    max_velocity: 3.4907
    has_acceleration_limits: false
    max_acceleration: 0
  joint24:
    has_velocity_limits: true
    max_velocity: 6.1087
    has_acceleration_limits: false
    max_acceleration: 0
  joint25:
    has_velocity_limits: true
    max_velocity: 6.1087
    has_acceleration_limits: false
    max_acceleration: 0
  joint26:
    has_velocity_limits: true
    max_velocity: 6.9813
    has_acceleration_limits: false
    max_acceleration: 0