// Generated by gencpp from file planner/PoseJ.msg
// DO NOT EDIT!


#ifndef PLANNER_MESSAGE_POSEJ_H
#define PLANNER_MESSAGE_POSEJ_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace planner
{
template <class ContainerAllocator>
struct PoseJ_
{
  typedef PoseJ_<ContainerAllocator> Type;

  PoseJ_()
    : joints()  {
      joints.assign(0.0);
  }
  PoseJ_(const ContainerAllocator& _alloc)
    : joints()  {
  (void)_alloc;
      joints.assign(0.0);
  }



   typedef boost::array<float, 6>  _joints_type;
  _joints_type joints;





  typedef boost::shared_ptr< ::planner::PoseJ_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::planner::PoseJ_<ContainerAllocator> const> ConstPtr;

}; // struct PoseJ_

typedef ::planner::PoseJ_<std::allocator<void> > PoseJ;

typedef boost::shared_ptr< ::planner::PoseJ > PoseJPtr;
typedef boost::shared_ptr< ::planner::PoseJ const> PoseJConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::planner::PoseJ_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::planner::PoseJ_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::planner::PoseJ_<ContainerAllocator1> & lhs, const ::planner::PoseJ_<ContainerAllocator2> & rhs)
{
  return lhs.joints == rhs.joints;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::planner::PoseJ_<ContainerAllocator1> & lhs, const ::planner::PoseJ_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace planner

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::planner::PoseJ_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::planner::PoseJ_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::planner::PoseJ_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::planner::PoseJ_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::planner::PoseJ_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::planner::PoseJ_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::planner::PoseJ_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3c5edcd2b7f6cf1cbc89957aadf54e64";
  }

  static const char* value(const ::planner::PoseJ_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3c5edcd2b7f6cf1cULL;
  static const uint64_t static_value2 = 0xbc89957aadf54e64ULL;
};

template<class ContainerAllocator>
struct DataType< ::planner::PoseJ_<ContainerAllocator> >
{
  static const char* value()
  {
    return "planner/PoseJ";
  }

  static const char* value(const ::planner::PoseJ_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::planner::PoseJ_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[6] joints\n"
;
  }

  static const char* value(const ::planner::PoseJ_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::planner::PoseJ_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.joints);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PoseJ_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::planner::PoseJ_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::planner::PoseJ_<ContainerAllocator>& v)
  {
    s << indent << "joints[]" << std::endl;
    for (size_t i = 0; i < v.joints.size(); ++i)
    {
      s << indent << "  joints[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.joints[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // PLANNER_MESSAGE_POSEJ_H
